export const SELECT_MOVIE = 'SELECT_MOVIE';
export const TOGGLE_FAVORITE_MOVIE = 'TOGGLE_FAVORITE_MOVIE';

export const MOVIES_FETCH = 'MOVIES_FETCH';
export const MOVIES_FETCH_SUCCESS = 'MOVIES_FETCH_SUCCESS';
export const MOVIES_FETCH_FAILED = 'MOVIES_FETCH_FAILED';

export const MOVIES_DETAILS_FETCH = 'MOVIES_DETAILS_FETCH';
export const MOVIES_DETAILS_FETCH_SUCCESS = 'MOVIES_DETAILS_FETCH_SUCCESS';
export const MOVIES_DETAILS_FETCH_FAILED = 'MOVIES_DETAILS_FETCH_FAILED';

export const MOVIES_REVIEWS_FETCH = 'MOVIES_REVIEWS_FETCH';
export const MOVIES_REVIEWS_FETCH_SUCCESS = 'MOVIES_REVIEWS_FETCH_SUCCESS';
export const MOVIES_REVIEWS_FETCH_FAILED = 'MOVIES_REVIEWS_FETCH_FAILED';

export const MOVIES_CREDITS_FETCH = 'MOVIES_CREDITS_FETCH';
export const MOVIES_CREDITS_FETCH_SUCCESS = 'MOVIES_CREDITS_FETCH_SUCCESS';
export const MOVIES_CREDITS_FETCH_FAILED = 'MOVIES_CREDITS_FETCH_FAILED';
