export const ROUTES = {
  ROOT_STACK: 'ROOT_STACK',

  AUTH_STACK: 'AUTH_STACK',
  AUTH: 'AUTH',

  TAB_STACK: 'TAB_STACK',
  MOVIES_STACK: 'MOVIES_STACK',
  MOVIES: 'MOVIES',
  DETAILS: 'DETAILS',

  FAVORITES_STACK: 'FAVORITES_STACK',
  FAVORITES: 'FAVORITES',
};
